export type DoorModeValue = "" | "manual" | "door" | "drawer";

export type CutlistRow = {
  id: string;
  room: string;
  partType: string;
  board: string;
  name: string;
  doorMode?: DoorModeValue;
  doorFrontCount?: string;
  doorTopGap?: string;
  doorBetweenGap?: string;
  doorBetweenGaps?: string[];
  doorSideLeft?: "front" | "panel";
  doorSideRight?: "front" | "panel";
  doorSideLeftGap?: string;
  doorSideRightGap?: string;
  doorFrontWidths?: string[];
  doorFrontWidthManual?: boolean[];
  doorFrontHeights?: string[];
  doorFrontHeightManual?: boolean[];
  doorFrontBoards?: string[];
  doorFrontBoardManual?: boolean[];
  doorFrontNames?: string[];
  doorFrontNameManual?: boolean[];
  doorFrontQuantities?: string[];
  doorFrontQuantityManual?: boolean[];
  height: string;
  width: string;
  depth: string;
  quantity: string;
  clashing: string;
  clashLeft?: string;
  clashRight?: string;
  fixedShelf?: string;
  adjustableShelf?: string;
  fixedShelfDrilling?: string;
  adjustableShelfDrilling?: string;
  hingesUp?: string[];
  hingesDown?: string[];
  information: string;
  grain: boolean;
  grainValue: string;
  includeInNesting?: boolean;
  parentName?: string;
  bankGroupId?: string;
  bankFrontIndexes?: number[];
};

export type CutlistDraftRow = CutlistRow;
export type CutlistEntryDraft = Omit<CutlistRow, "id" | "room">;
